name: sync2gitee
# version: 1.0.2
# author: [yiXu](https://github.com/yi-Xu-0100)
# guide: [yi-Xu-0100/hub-mirror](https://github.com/yi-Xu-0100/hub-mirror)
# template: [sync2gitee.yml](https://github.com/yi-Xu-0100/hub-mirror/blob/main/template/sync2gitee.yml)
# lastmod: 2021-01-29 23:05:54

#on:
#  push:
#  schedule:
#    # UTC 21:00 -> CST (China) 5:00 see https://datetime360.com/cn/utc-cst-china-time/
#    - cron: '1 21 * * *'

on:
  push:
    branches:
      - main

jobs:
  run:
    name: Sync GitHub to Gitee
    runs-on: ubuntu-latest
    steps:

      - name: Mirror the GitHub repos to Gitee
        uses: Yikun/hub-mirror-action@v1.3
        with:
          src: github/dgoeee
          dst: gitee/dgoeee
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          dst_token: ${{ secrets.GITEE_TOKEN }}
          account_type: user
          force_update: true
          timeout: 300